import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Login
    'login.welcome': 'Bienvenue',
    'login.subtitle': 'Connectez-vous à votre espace gestionnaire.',
    'login.username': "Nom d'utilisateur",
    'login.password': 'Mot de passe',
    'login.login': 'Se connecter',
    'login.loading': 'Chargement...',
    'login.error': 'Identifiant ou mot de passe incorrect.',
    'login.back': 'Retour',
    'login.contact_support': 'Contactez le support',
    'login.no_account': 'Pas encore de compte ?',

    // Sidebar
    'nav.dashboard': 'Tableau de bord',
    'nav.sales': 'Vente & Caisse',
    'nav.inventory': 'Stock & Formules',
    'nav.employees': 'Gestion des Employés et Rôles',
    'nav.finance': 'Finance & Depenses',
    'nav.advisor': 'Assistant IA',
    'nav.settings': 'Paramètres',
    'nav.guide': 'Guide Utilisateur',
    'nav.logout': 'Déconnexion',
    'nav.profile': 'Mon Profil',
    'nav.analytics': 'Analyses',
    'nav.invoices': 'Factures',
    'nav.boutiques': 'Boutique',
    'nav.accounting': 'Comptabilité',
    'nav.provenderies': 'Provenderies',
    'nav.back_to_hub': 'Retour au Hub',
    'nav.secured_core_desc': 'Algorithmes de ration optimisés actifs.',
    'nav.install_app': "Installer l'App",

    // Dashboard
    'dashboard.title': 'Tableau de Bord',
    'dashboard.subtitle': "Vue d'ensemble de votre activité aujourd'hui.",
    'dashboard.revenue_today': "Chiffre d'Affaires",
    'dashboard.sales_count': 'Ventes Réalisées',
    'dashboard.low_stock': 'Alertes Stock',
    'dashboard.active_employees': 'Employés Actifs',
    'dashboard.recent_sales': 'Ventes Récentes',
    'dashboard.top_products': 'Produits Phares',
    'dashboard.no_sales': 'Aucune vente aujourd\'hui',
    'dashboard.revenue_category_boutique': 'Revenus par Catégorie & Boutique',
    'dashboard.boutique_performance': 'Performance Boutiques',
    'dashboard.open': 'Ouvert',
    'dashboard.closed': 'Fermé',
    'dashboard.debts': 'Dettes',
    'dashboard.no_boutique': 'Aucune boutique configurée.',
    'dashboard.customer_debts': 'Dettes Clients',
    'dashboard.uncollected': 'Non recouvré',
    'dashboard.real_time': 'Temps réel',
    'dashboard.stable_inventory': 'Inventaire stable',

    // Sales
    'sales.title': 'Caisse & Vente',
    'sales.subtitle': 'Gérez vos ventes et encaissements.',
    'sales.new_sale': 'Nouvelle Vente',
    'sales.search_product': 'Rechercher un produit...',
    'sales.cart': 'Panier',
    'sales.empty_cart': 'Votre panier est vide',
    'sales.total': 'Total',
    'sales.checkout': 'Encaisser',
    'sales.customer': 'Client',
    'sales.payment_method': 'Moyen de Paiement',
    'sales.amount_received': 'Montant Reçu',
    'sales.change': 'Monnaie à rendre',
    'sales.confirm': 'Confirmer la Vente',
    'sales.cancel': 'Annuler',
    'sales.success': 'Vente enregistrée avec succès',

    // Inventory
    'inventory.title': 'Stock & Inventaire',
    'inventory.subtitle': 'Gérez vos produits et niveaux de stock.',
    'inventory.add_product': 'Nouveau Produit',
    'inventory.search': 'Rechercher un produit...',
    'inventory.name': 'Nom',
    'inventory.category': 'Catégorie',
    'inventory.price': 'Prix',
    'inventory.stock': 'Stock',
    'inventory.actions': 'Actions',
    'inventory.low_stock_warning': 'Stock Faible',
    'inventory.edit': 'Modifier',
    'inventory.delete': 'Supprimer',
    'inventory.save': 'Enregistrer',
    'inventory.cancel': 'Annuler',
    'inventory.mixer': 'Mélangeur',
    'inventory.mixer_subtitle': 'Gestion de production et formules',
    'inventory.production': 'Production',
    'inventory.formulas': 'Formules',
    'inventory.history': 'Historique',
    'inventory.raw_materials': 'Matières Premières',
    'inventory.health': 'Santé',
    'inventory.equipment': 'Matériel',
    'inventory.food': 'Formules & Aliments',
    'inventory.total_products': 'Produits Total',
    'inventory.low_stock': 'Stock Faible',
    'inventory.stock_value': 'Valeur Stock',
    'inventory.edit_product': 'Modifier Produit',
    'inventory.product_name': 'Nom du produit',
    'inventory.cost_price': 'Prix d\'Achat / Coût',
    'inventory.unit': 'Unité',
    'inventory.low_stock_threshold': 'Seuil d\'alerte',
    'inventory.description': 'Description',
    'inventory.variants': 'Variantes',
    'inventory.add_variant': 'Ajouter Variante',
    'inventory.variant_name': 'Nom Variante',
    'inventory.wholesale_price': 'Prix Gros',
    'inventory.confirm_delete': 'Confirmer la suppression',
    'inventory.confirm_delete_msg': 'Êtes-vous sûr de vouloir supprimer ce produit ?',
    'inventory.restock': 'Réapprovisionner',
    'inventory.quantity': 'Quantité',
    'inventory.note': 'Note / Référence',
    'inventory.date': 'Date',
    'inventory.buying_price': 'Prix d\'Achat (Unitaire)',
    'inventory.selling_price': 'Nouveau Prix Vente',
    'inventory.update_stock': 'Mettre à jour Stock',
    'inventory.production_summary': 'Résumé Production',
    'inventory.ingredients': 'Ingrédients',
    'inventory.total_weight': 'Poids Total',
    'inventory.cost_per_kg': 'Coût par kg',
    'inventory.suggested_retail': 'Prix Vente Suggéré',
    'inventory.print': 'Imprimer',
    'inventory.confirm_production': 'Confirmer Production',
    'inventory.restock_title': 'Réapprovisionnement',
    'inventory.entry_details': 'Détails Entrée',
    'inventory.added_quantity': 'Quantité Ajoutée',
    'inventory.price_update': 'Mise à jour Prix',
    'inventory.buying_price_cost': 'Prix Achat (Coût)',
    'inventory.selling_price_retail': 'Prix Vente (Détail)',
    'inventory.selling_price_wholesale': 'Prix Vente (Gros)',
    'inventory.validate_stock_entry': 'Valider Entrée Stock',
    'inventory.edit_variant': 'Modifier Variante',
    'inventory.new_product': 'Nouveau Produit',
    'inventory.stock_unit': 'Unité de Stock',
    'inventory.select_unit': 'Sélectionner une unité',
    'inventory.buying_price_default': 'Coût Achat (Défaut)',
    'inventory.selling_price_default': 'Prix Vente (Défaut)',
    'inventory.low_stock_threshold_label': 'Seuil Stock Bas',
    'inventory.variants_section': 'Variantes / Conditionnements',
    'inventory.variants_help': 'Ajoutez des variantes si le produit a plusieurs tailles/prix.',
    'inventory.add': 'Ajouter',
    'inventory.no_variants_defined': 'Aucune variante définie. Ajoutez-en une ci-dessus.',
    'inventory.save_variant': 'Enregistrer Variante',
    'inventory.save_product': 'Enregistrer Produit',
    'inventory.delete_product_title': 'Supprimer le produit',
    'inventory.delete_product_confirm': 'Êtes-vous sûr de vouloir supprimer le produit',
    'inventory.irreversible_action': 'Cette action est irréversible.',
    'inventory.formulas_reset': 'Formules existantes supprimées (Reset)',
    'inventory.product_name_required': 'Le nom du produit est requis',
    'inventory.variant_name_required': 'Le nom de la variante est requis',
    'inventory.variant_price_invalid': 'Le prix de la variante est invalide',
    'inventory.variant_updated': 'Variante modifiée',
    'inventory.variants_in_stock': 'Variantes en Stock',
    'inventory.variant': 'Variante',
    'inventory.initial_stock': 'Stock Initial',
    'inventory.new_formula': 'Nouvelle Formule',
    'inventory.no_formulas': 'Aucune formule créée. Cliquez sur "Nouvelle Formule" pour commencer.',
    'inventory.retail_short': 'Vente',
    'inventory.wholesale_short': 'Gros',
    'inventory.cost_short': 'Coût',
    'inventory.my_formulas': 'Mes Formules',
    'inventory.my_formulas_desc': 'Gérez vos recettes et compositions',
    'inventory.in_stock': 'en stock',
    'inventory.available_ingredients': 'Ingrédients Disponibles',

    // Employees
    'employees.title': 'Gestion du Personnel',
    'employees.subtitle': 'Gérez votre équipe et leurs accès.',
    'employees.add_employee': 'Nouvel Employé',
    'employees.search': 'Rechercher un employé...',
    'employees.name': 'Nom',
    'employees.role': 'Rôle',
    'employees.boutique': 'Boutique',
    'employees.contact': 'Contact',
    'employees.salary': 'Salaire / Ration',
    'employees.actions': 'Actions',
    'employees.pay_salary': 'Payer Salaire',
    'employees.give_ration': 'Donner Ration',
    'employees.edit': 'Modifier',
    'employees.delete': 'Supprimer',
    'employees.save': 'Enregistrer',
    'employees.cancel': 'Annuler',
    'employees.confirm_delete': 'Supprimer l\'employé ?',
    'employees.confirm_delete_msg': 'Êtes-vous sûr de vouloir supprimer cet employé ?',

    // Finance
    'finance.title': 'Finance & Dépenses',
    'finance.subtitle': 'Suivez vos flux financiers.',
    'finance.add_expense': 'Nouvelle Dépense',
    'finance.expenses': 'Dépenses',
    'finance.income': 'Revenus',
    'finance.balance': 'Solde',
    'finance.category': 'Catégorie',
    'finance.amount': 'Montant',
    'finance.date': 'Date',
    'finance.description': 'Description',

    // Settings
    'settings.title': 'Paramètres',
    'settings.subtitle': 'Personnalisez votre expérience Smart Agro',
    'settings.company_identity': "Identité de l'Entreprise",
    'settings.company_name': "Nom de l'entreprise",
    'settings.company_name_desc': "Ce nom apparaîtra sur les factures et dans l'interface.",
    'settings.language': 'Langue / Language',
    'settings.appearance': 'Apparence',
    'settings.color_theme': 'Thème de couleur',
    'settings.display_mode': "Mode d'affichage",
    'settings.light': 'Clair',
    'settings.dark': 'Sombre',
    'settings.auto': 'Auto',
    'settings.save': 'Enregistrer les modifications',
    'settings.saved': 'Paramètres enregistrés avec succès',

    // Profile
    'profile.title': 'Mon Profil',
    'profile.subtitle': "Vue d'ensemble",
    'profile.email': 'Email',
    'profile.boutique': 'Boutique',
    'profile.emergency_contact': "Contact d'Urgence",
    'profile.contact_name': 'Nom du contact',
    'profile.relation': 'Relation (ex: Père)',
    'profile.phone': 'Téléphone (Urgence)',
    'profile.salary_advances': 'Salaires & Avances',
    'profile.total_received': 'Total Perçu (Historique)',
    'profile.no_salary_history': 'Aucun historique de salaire.',
    'profile.click_to_show': 'Cliquez pour afficher les détails',
    'profile.performance': 'Performance',
    'profile.active': 'Active',
    'profile.account_operational': 'Compte opérationnel',
    'profile.contact_updated': "Contact d'urgence mis à jour",
    'profile.update_error': "Erreur lors de la mise à jour",

    // Common
    'common.loading': 'Chargement...',
    'common.error': 'Une erreur est survenue',
    'common.success': 'Succès',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.search': 'Rechercher...',
    'common.filter': 'Filtrer',
    'common.all': 'Tous',
    'common.none': 'Aucun',
    'common.not_provided': 'Non renseigné',
    'common.today': "Aujourd'hui",
    'common.this_week': "Cette Semaine",
    'common.this_month': "Ce Mois",
    'common.this_year': "Cette Année",
    'common.all_history': "Tout l'historique",
    'common.all_categories': "Tous les rayons",

    // Landing
    'landing.connexion_admin': 'Connexion Espace Admin',
    'landing.solution_provenderies': 'Solution #1 pour Provenderies',
    'landing.title_main': 'Comment gérer votre',
    'landing.title_main_bold': 'provenderie ?',
    'landing.title_sub': "C'est simple !",
    'landing.desc': "Prenez les commandes de vos flux d'inventaire, automatisez la fabrication de vos aliments et pilotez votre force de vente avec réactivité.",
    'landing.start_now': 'DÉMARRER MAINTENANT',
    'landing.sync_desc': 'Base locale sécurisée & Cloud Sync',
    'landing.happy_clients': 'Clients Heureux',
    'landing.availability': 'Disponibilité',
    'landing.live_system': 'Système Actif',
    'landing.stock_alert': 'Alerte Stock',
    'landing.feed_alert': 'Maïs bas ! (-30%)',
    'landing.performance': 'Performance',
    'landing.sales_increase': '+24.5% ventes',
    'landing.synchronized': 'Synchronisé',
    'landing.secured_engine': 'Moteur Sécurisé',
    'landing.need': 'Tout ce dont vous avez besoin',
    'landing.need_desc': 'Une suite complète d\'outils conçus spécifiquement pour les provenderies et commerces agricoles.',
    'landing.feat1_title': 'Gestion de Stock',
    'landing.feat1_desc': 'Suivez vos matières premières et produits finis en temps réel. Alertes de stock bas automatiques.',
    'landing.feat2_title': 'Analyses Financières',
    'landing.feat2_desc': 'Visualisez vos marges, profits et dépenses. Prenez des décisions basées sur des données réelles.',
    'landing.feat3_title': 'Gestion Clients',
    'landing.feat3_desc': 'Suivez les dettes et crédits clients facilement. Facturation professionnelle et historique complet.',
    'landing.rights': 'Tous droits réservés.',
    'landing.privacy': 'Politique de Confidentialité',
    'landing.terms': 'Conditions d\'Utilisation',
    'landing.security': 'Sécurité',
    'landing.privacy_title': 'Politique de Confidentialité',
    'landing.terms_title': 'Conditions d\'Utilisation',
    'landing.security_title': 'Sécurité des Données',
    'landing.understood_close': 'J\'ai compris, fermer',
    'landing.last_update': 'Dernière mise à jour',
    'landing.decl_title': 'Déclaration de Confidentialité et Sécurité :',
    'landing.decl_text': 'Nous prenons la sécurité de vos données très au sérieux. Toutes les informations enregistrées sur cette plateforme (stocks, ventes, données clients) sont cryptées et stockées de manière sécurisée. L\'accès à votre compte est strictement personnel. Nous ne partageons aucune de vos données commerciales avec des tiers sans votre consentement explicite. En utilisant cette application, vous acceptez nos conditions générales d\'utilisation et notre politique de traitement des données.',
    'landing.p1_title': 'Collecte Minimale',
    'landing.p1_desc': 'Nous collectons uniquement les données strictement nécessaires au fonctionnement de votre commerce : état des stocks, historique des ventes, et gestion des employés. Aucune donnée superflue n\'est requise.',
    'landing.p2_title': 'Utilisation Interne',
    'landing.p2_desc': 'Ces données sont utilisées exclusivement pour vous fournir des rapports détaillés, des analyses de performance et assurer le bon fonctionnement de l\'application Smart Agro.',
    'landing.p3_title': 'Zéro Partage',
    'landing.p3_desc': 'Vos données vous appartiennent. Aucune information n\'est vendue, louée ou partagée avec des tiers publicitaires ou des partenaires commerciaux externes.',
    'landing.t1_title': 'Acceptation',
    'landing.t1_desc': 'L\'utilisation de ce logiciel implique l\'acceptation pleine et entière des présentes conditions. En accédant à la plateforme, vous vous engagez à respecter ces règles d\'utilisation.',
    'landing.t2_title': 'Responsabilité',
    'landing.t2_desc': 'Smart Agro fournit l\'outil de gestion mais ne saurait être tenu responsable des erreurs de saisie manuelles ou des pertes d\'exploitation liées à une mauvaise utilisation du logiciel.',
    'landing.t3_title': 'Licence d\'Usage',
    'landing.t3_desc': 'Ce logiciel est concédé sous licence d\'utilisation exclusive à votre entreprise. Toute reproduction ou revente de la solution logicielle est strictement interdite.',
    'landing.s1_title': 'Chiffrement',
    'landing.s1_desc': 'Toutes les communications entre votre appareil et nos serveurs sont chiffrées via des protocoles SSL/HTTPS de dernière génération, garantissant l\'intégrité de vos transactions.',
    'landing.s2_title': 'Contrôle d\'Accès',
    'landing.s2_desc': 'L\'accès est protégé par une authentification robuste. Il est de votre responsabilité de garder vos mots de passe confidentiels et de gérer les rôles de vos employés avec précaution.',
    'landing.s3_title': 'Sauvegardes',
    'landing.s3_desc': 'Des sauvegardes régulières et redondantes sont effectuées automatiquement dans le cloud pour prévenir toute perte de données en cas de défaillance matérielle.',

    // Hub
    'hub.nav.hub_grid': 'MANAGEMENT GRID',
    'hub.nav.home': 'Accueil',
    'hub.nav.modules': 'Nos Modules',
    'hub.nav.technical': 'Espace Technique',
    'hub.nav.assistance': 'Assistance',
    'hub.header.dashboard': 'Tableau de bord de gestion',
    'hub.header.welcome': 'Bonjour, ',
    'hub.header.connected_role_prefix': 'Vous êtes connecté avec le rôle ',
    'hub.header.connected_role_suffix': '. Sélectionnez un des modules ci-dessous pour démarrer vos opérations.',
    'hub.header.active_session': 'Session Active',
    'hub.section.magasin_title': 'Gestion de Magasin',
    'hub.section.magasin_subtitle': 'Inventaire & Production',
    'hub.section.magasin_description': 'Supervision de stock en temps réel, création & calcul automatique de formules de nutrition animale et approvisionnement des boutiques.',
    'hub.section.magasin_badge': 'Cœur Opérationnel',
    'hub.section.magasin_f1': 'Suivi de stock & alertes de seuil critique',
    'hub.section.magasin_f2': 'Calculateur de formules optimisées',
    'hub.section.magasin_f3': 'Gestion multisites & transferts',
    'hub.section.magasin_tag': 'Magasin & Production',
    'hub.section.facturation_title': 'Caisse & Facturation',
    'hub.section.facturation_subtitle': 'Points de Vente & Clients',
    'hub.section.facturation_description': 'Enregistrement ultra-rapide des ventes, factures normalisées, gestion de caisse et des acomptes/dettes de vos clients.',
    'hub.section.facturation_badge': 'Générateur de Richesse',
    'hub.section.facturation_f1': 'Caisse tactile (POS) ultra-rapide',
    'hub.section.facturation_f2': 'Suivi rigoureux des crédits & avances',
    'hub.section.facturation_f3': 'Facturation et reçus conformes',
    'hub.section.facturation_tag': 'Ventes & Cashflow',
    'hub.section.comptabilite_title': 'Comptabilité',
    'hub.section.comptabilite_subtitle': 'Analyses & Dépenses',
    'hub.section.comptabilite_description': 'Centralisation des flux financiers, journal des d’épenses d’exploitation et rapports de performance pour guider vos choix.',
    'hub.section.comptabilite_badge': 'Pilotage Décisionnel',
    'hub.section.comptabilite_f1': 'Bilan automatique des bénéfices',
    'hub.section.comptabilite_f2': 'Enregistrement structuré des charges',
    'hub.section.comptabilite_f3': 'Suivi du chiffre d’affaires brut',
    'hub.section.comptabilite_tag': 'Finance & Stratégie',
    'hub.section.administration_title': 'Administration',
    'hub.section.administration_subtitle': 'Contrôle & Sécurité',
    'hub.section.administration_description': 'Gestion sécurisée des collaborateurs, distribution des rôles d’accès et audit global des activités par provenderie.',
    'hub.section.administration_badge': 'Sécurisé & Conforme',
    'hub.section.administration_f1': 'Fiches administratifs des employés',
    'hub.section.administration_f2': 'Rôles personnalisés & permissions',
    'hub.section.administration_f3': 'Paramètres globaux de la structure',
    'hub.section.administration_tag': 'Équipe & Droits',
    'hub.labels.operational_modules': 'Modules Opérationnels',
    'hub.labels.management_pilot': 'Gestion & Pilotage',
    'hub.labels.open_space': 'Ouvrir l’Espace',
    'hub.labels.access': 'Accéder',
  },
  en: {
    // Login
    'login.welcome': 'Welcome',
    'login.subtitle': 'Log in to your management dashboard.',
    'login.username': 'Username',
    'login.password': 'Password',
    'login.login': 'Log In',
    'login.loading': 'Loading...',
    'login.error': 'Incorrect username or password.',
    'login.back': 'Back',
    'login.contact_support': 'Contact Support',
    'login.no_account': 'No account yet?',

    // Sidebar
    'nav.dashboard': 'Dashboard',
    'nav.sales': 'Sales & POS',
    'nav.inventory': 'Stock & Formulas',
    'nav.employees': 'Employee & Role Management',
    'nav.finance': 'Finance & Expenses',
    'nav.advisor': 'AI Assistant',
    'nav.settings': 'Settings',
    'nav.guide': 'User Guide',
    'nav.logout': 'Logout',
    'nav.profile': 'My Profile',
    'nav.analytics': 'Analytics',
    'nav.invoices': 'Invoices',
    'nav.boutiques': 'Boutique',
    'nav.accounting': 'Accounting',
    'nav.provenderies': 'Feed Mills',
    'nav.back_to_hub': 'Back to Hub',
    'nav.secured_core_desc': 'Optimized feed formulation algorithms active.',
    'nav.install_app': 'Install App',

    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': "Overview of today's activity.",
    'dashboard.revenue_today': 'Revenue Today',
    'dashboard.sales_count': 'Sales Count',
    'dashboard.low_stock': 'Low Stock Alerts',
    'dashboard.active_employees': 'Active Staff',
    'dashboard.recent_sales': 'Recent Sales',
    'dashboard.top_products': 'Top Products',
    'dashboard.no_sales': 'No sales today',
    'dashboard.revenue_category_boutique': 'Revenue by Category & Boutique',
    'dashboard.boutique_performance': 'Boutique Performance',
    'dashboard.open': 'Open',
    'dashboard.closed': 'Closed',
    'dashboard.debts': 'Debts',
    'dashboard.no_boutique': 'No boutique configured.',
    'dashboard.customer_debts': 'Customer Debts',
    'dashboard.uncollected': 'Uncollected',
    'dashboard.real_time': 'Real-time',
    'dashboard.stable_inventory': 'Stable Inventory',

    // Sales
    'sales.title': 'Sales & POS',
    'sales.subtitle': 'Manage your sales and payments.',
    'sales.new_sale': 'New Sale',
    'sales.search_product': 'Search product...',
    'sales.cart': 'Cart',
    'sales.empty_cart': 'Your cart is empty',
    'sales.total': 'Total',
    'sales.checkout': 'Checkout',
    'sales.customer': 'Customer',
    'sales.payment_method': 'Payment Method',
    'sales.amount_received': 'Amount Received',
    'sales.change': 'Change',
    'sales.confirm': 'Confirm Sale',
    'sales.cancel': 'Cancel',
    'sales.success': 'Sale recorded successfully',

    // Inventory
    'inventory.title': 'Stock & Inventory',
    'inventory.subtitle': 'Manage products and stock levels.',
    'inventory.add_product': 'New Product',
    'inventory.search': 'Search product...',
    'inventory.name': 'Name',
    'inventory.category': 'Category',
    'inventory.price': 'Price',
    'inventory.stock': 'Stock',
    'inventory.actions': 'Actions',
    'inventory.low_stock_warning': 'Low Stock',
    'inventory.edit': 'Edit',
    'inventory.delete': 'Delete',
    'inventory.save': 'Save',
    'inventory.cancel': 'Cancel',
    'inventory.mixer': 'Mixer',
    'inventory.mixer_subtitle': 'Production and formula management',
    'inventory.production': 'Production',
    'inventory.formulas': 'Formulas',
    'inventory.history': 'History',
    'inventory.raw_materials': 'Raw Materials',
    'inventory.health': 'Health',
    'inventory.equipment': 'Equipment',
    'inventory.food': 'Formulas & Feed',
    'inventory.total_products': 'Total Products',
    'inventory.low_stock': 'Low Stock',
    'inventory.stock_value': 'Stock Value',
    'inventory.edit_product': 'Edit Product',
    'inventory.product_name': 'Product Name',
    'inventory.cost_price': 'Cost Price',
    'inventory.unit': 'Unit',
    'inventory.low_stock_threshold': 'Alert Threshold',
    'inventory.description': 'Description',
    'inventory.variants': 'Variants',
    'inventory.add_variant': 'Add Variant',
    'inventory.variant_name': 'Variant Name',
    'inventory.wholesale_price': 'Wholesale Price',
    'inventory.confirm_delete': 'Confirm delete',
    'inventory.confirm_delete_msg': 'Are you sure you want to delete this product?',
    'inventory.restock': 'Restock',
    'inventory.quantity': 'Quantity',
    'inventory.note': 'Note / Reference',
    'inventory.date': 'Date',
    'inventory.buying_price': 'Buying Price (Unit)',
    'inventory.selling_price': 'New Selling Price',
    'inventory.update_stock': 'Update Stock',
    'inventory.production_summary': 'Production Summary',
    'inventory.ingredients': 'Ingredients',
    'inventory.total_weight': 'Total Weight',
    'inventory.cost_per_kg': 'Cost per kg',
    'inventory.suggested_retail': 'Suggested Retail Price',
    'inventory.print': 'Print',
    'inventory.confirm_production': 'Confirm Production',
    'inventory.restock_title': 'Restock',
    'inventory.entry_details': 'Entry Details',
    'inventory.added_quantity': 'Added Quantity',
    'inventory.price_update': 'Price Update',
    'inventory.buying_price_cost': 'Buying Price (Cost)',
    'inventory.selling_price_retail': 'Selling Price (Retail)',
    'inventory.selling_price_wholesale': 'Selling Price (Wholesale)',
    'inventory.validate_stock_entry': 'Validate Stock Entry',
    'inventory.edit_variant': 'Edit Variant',
    'inventory.new_product': 'New Product',
    'inventory.stock_unit': 'Stock Unit',
    'inventory.select_unit': 'Select a unit',
    'inventory.buying_price_default': 'Buying Price (Default)',
    'inventory.selling_price_default': 'Selling Price (Default)',
    'inventory.low_stock_threshold_label': 'Low Stock Threshold',
    'inventory.variants_section': 'Variants / Packaging',
    'inventory.variants_help': 'Add variants if the product has multiple sizes/prices.',
    'inventory.add': 'Add',
    'inventory.no_variants_defined': 'No variants defined. Add one above.',
    'inventory.save_variant': 'Save Variant',
    'inventory.save_product': 'Save Product',
    'inventory.delete_product_title': 'Delete Product',
    'inventory.delete_product_confirm': 'Are you sure you want to delete the product',
    'inventory.irreversible_action': 'This action is irreversible.',
    'inventory.formulas_reset': 'Existing formulas reset',
    'inventory.product_name_required': 'Product name is required',
    'inventory.variant_name_required': 'Variant name is required',
    'inventory.variant_price_invalid': 'Invalid variant price',
    'inventory.variant_updated': 'Variant updated',
    'inventory.variants_in_stock': 'Variants in Stock',
    'inventory.variant': 'Variant',
    'inventory.initial_stock': 'Initial Stock',
    'inventory.new_formula': 'New Formula',
    'inventory.no_formulas': 'No formulas created. Click "New Formula" to start.',
    'inventory.retail_short': 'Retail',
    'inventory.wholesale_short': 'Wholesale',
    'inventory.cost_short': 'Cost',
    'inventory.my_formulas': 'My Formulas',
    'inventory.my_formulas_desc': 'Manage your recipes and compositions',
    'inventory.in_stock': 'in stock',
    'inventory.available_ingredients': 'Available Ingredients',

    // Employees
    'employees.title': 'Staff Management',
    'employees.subtitle': 'Manage your team and access.',
    'employees.add_employee': 'New Employee',
    'employees.search': 'Search employee...',
    'employees.name': 'Name',
    'employees.role': 'Role',
    'employees.boutique': 'Shop',
    'employees.contact': 'Contact',
    'employees.salary': 'Salary / Ration',
    'employees.actions': 'Actions',
    'employees.pay_salary': 'Pay Salary',
    'employees.give_ration': 'Give Ration',
    'employees.edit': 'Edit',
    'employees.delete': 'Delete',
    'employees.save': 'Save',
    'employees.cancel': 'Cancel',
    'employees.confirm_delete': 'Delete Employee?',
    'employees.confirm_delete_msg': 'Are you sure you want to delete this employee?',

    // Finance
    'finance.title': 'Finance & Expenses',
    'finance.subtitle': 'Track your financial flows.',
    'finance.add_expense': 'New Expense',
    'finance.expenses': 'Expenses',
    'finance.income': 'Income',
    'finance.balance': 'Balance',
    'finance.category': 'Category',
    'finance.amount': 'Amount',
    'finance.date': 'Date',
    'finance.description': 'Description',

    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'Customize your Smart Agro experience',
    'settings.company_identity': 'Company Identity',
    'settings.company_name': 'Company Name',
    'settings.company_name_desc': 'This name will appear on invoices and in the interface.',
    'settings.language': 'Language',
    'settings.appearance': 'Appearance',
    'settings.color_theme': 'Color Theme',
    'settings.display_mode': 'Display Mode',
    'settings.light': 'Light',
    'settings.dark': 'Dark',
    'settings.auto': 'Auto',
    'settings.save': 'Save Changes',
    'settings.saved': 'Settings saved successfully',

    // Profile
    'profile.title': 'My Profile',
    'profile.subtitle': 'Overview',
    'profile.email': 'Email',
    'profile.boutique': 'Shop',
    'profile.emergency_contact': 'Emergency Contact',
    'profile.contact_name': 'Contact Name',
    'profile.relation': 'Relationship (e.g. Father)',
    'profile.phone': 'Phone (Emergency)',
    'profile.salary_advances': 'Salary & Advances',
    'profile.total_received': 'Total Received (History)',
    'profile.no_salary_history': 'No salary history.',
    'profile.click_to_show': 'Click to view details',
    'profile.performance': 'Performance',
    'profile.active': 'Active',
    'profile.account_operational': 'Account operational',
    'profile.contact_updated': 'Emergency contact updated',
    'profile.update_error': 'Error updating contact',

    // Common
    'common.loading': 'Loading...',
    'common.error': 'An error occurred',
    'common.success': 'Success',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.search': 'Search...',
    'common.filter': 'Filter',
    'common.all': 'All',
    'common.none': 'None',
    'common.not_provided': 'Not provided',
    'common.today': "Today",
    'common.this_week': "This Week",
    'common.this_month': "This Month",
    'common.this_year': "This Year",
    'common.all_history': "All History",
    'common.all_categories': "All Categories",

    // Landing
    'landing.connexion_admin': 'Admin Portal Connection',
    'landing.solution_provenderies': '#1 Solution for Feed Mills',
    'landing.title_main': 'How to manage your',
    'landing.title_main_bold': 'feed mill?',
    'landing.title_sub': "It's easy!",
    'landing.desc': 'Take command of your inventory flows, automate your feed production, and manage your sales force responsively.',
    'landing.start_now': 'START NOW',
    'landing.sync_desc': 'Secure Local Database & Cloud Sync',
    'landing.happy_clients': 'Happy Clients',
    'landing.availability': 'Availability',
    'landing.live_system': 'Live System',
    'landing.stock_alert': 'Stock Alert',
    'landing.feed_alert': 'Corn low! (-30%)',
    'landing.performance': 'Performance',
    'landing.sales_increase': '+24.5% sales',
    'landing.synchronized': 'Synchronized',
    'landing.secured_engine': 'Secured Engine',
    'landing.need': 'Everything You Need',
    'landing.need_desc': 'A complete suite of tools designed specifically for feed mills and agricultural shops.',
    'landing.feat1_title': 'Stock Management',
    'landing.feat1_desc': 'Track your raw materials and finished products in real time. Automatic low stock alerts.',
    'landing.feat2_title': 'Financial Analytics',
    'landing.feat2_desc': 'Visualize your margins, profits, and expenses. Make informed decisions based on real data.',
    'landing.feat3_title': 'Client Management',
    'landing.feat3_desc': 'Easily track client debts and credits. Professional invoicing and complete transaction history.',
    'landing.rights': 'All rights reserved.',
    'landing.privacy': 'Privacy Policy',
    'landing.terms': 'Terms of Use',
    'landing.security': 'Security',
    'landing.privacy_title': 'Privacy Policy',
    'landing.terms_title': 'Terms of Use',
    'landing.security_title': 'Data Security',
    'landing.understood_close': 'I understand, close',
    'landing.last_update': 'Last updated',
    'landing.decl_title': 'Privacy and Security Statement:',
    'landing.decl_text': 'We take the security of your data extremely seriously. All information recorded on this platform (stocks, sales, client data) is encrypted and stored securely. Access to your account is strictly personal. We do not share any of your business data with third parties without your explicit consent. By using this application, you agree to our general terms of use and our data processing policy.',
    'landing.p1_title': 'Minimal Collection',
    'landing.p1_desc': 'We only collect data strictly necessary for your business operations: stock levels, sale history, and employee management. No unnecessary information is required.',
    'landing.p2_title': 'Internal Use Only',
    'landing.p2_desc': 'This data is used exclusively to produce detailed reports, perform performance analysis, and ensure the optimal operation of the Smart Agro application.',
    'landing.p3_title': 'Zero Sharing',
    'landing.p3_desc': 'Your data belongs to you. No information is ever sold, rented, or shared with third-party advertisers or external commercial partners.',
    'landing.t1_title': 'Acceptation',
    'landing.t1_desc': 'By using this software, you fully accept and agree to these terms. Accessing the platform commits you to respecting these rules of use.',
    'landing.t2_title': 'Liability',
    'landing.t2_desc': 'Smart Agro provides the management system but cannot be held liable for manual entry mistakes or financial/operational losses resulting from improper software usage.',
    'landing.t3_title': 'Access License',
    'landing.t3_desc': 'This software is granted under an exclusive personal license to your company. Any reproduction or resale of this software is strictly forbidden.',
    'landing.s1_title': 'Encryption',
    'landing.s1_desc': 'All communications between your device and our servers are encrypted using state-of-the-art SSL/HTTPS protocols, ensuring the absolute integrity of your transactions.',
    'landing.s2_title': 'Access Control',
    'landing.s2_desc': 'Access is strictly protected by robust authentication. It is your responsibility to keep passwords confidential and carefully manage employee roles.',
    'landing.s3_title': 'Backups',
    'landing.s3_desc': 'Regular and redundant backups are automatically created in the cloud to prevent any data loss in case of physical device hardware failures.',

    // Hub
    'hub.nav.hub_grid': 'MANAGEMENT GRID',
    'hub.nav.home': 'Home',
    'hub.nav.modules': 'Our Modules',
    'hub.nav.technical': 'Technical Space',
    'hub.nav.assistance': 'Support',
    'hub.header.dashboard': 'Management Dashboard',
    'hub.header.welcome': 'Hello, ',
    'hub.header.connected_role_prefix': 'You are logged in with the role ',
    'hub.header.connected_role_suffix': '. Select one of the modules below to start your operations.',
    'hub.header.active_session': 'Active Session',
    'hub.section.magasin_title': 'Store Management',
    'hub.section.magasin_subtitle': 'Inventory & Production',
    'hub.section.magasin_description': 'Real-time stock tracking, automatic Formulation of feed formulation and store provisioning.',
    'hub.section.magasin_badge': 'Operational Core',
    'hub.section.magasin_f1': 'Stock tracking & critical alerts',
    'hub.section.magasin_f2': 'Formulation & nutrition calculator',
    'hub.section.magasin_f3': 'Multisite tracking & physical transfers',
    'hub.section.magasin_tag': 'Store & Production',
    'hub.section.facturation_title': 'POS & Invoicing',
    'hub.section.facturation_subtitle': 'Shops & Customers',
    'hub.section.facturation_description': 'Lightning-fast sales recording, normalized bills & invoices, cash register, and customer debts / pre-payments tracking.',
    'hub.section.facturation_badge': 'Wealth Generator',
    'hub.section.facturation_f1': 'Touch-screen register (POS) ultra fast',
    'hub.section.facturation_f2': 'Debts and credits bookkeeping',
    'hub.section.facturation_f3': 'Standard billing and receipts',
    'hub.section.facturation_tag': 'Sales & Cashflow',
    'hub.section.comptabilite_title': 'Accounting',
    'hub.section.comptabilite_subtitle': 'Analytics & Expenses',
    'hub.section.comptabilite_description': 'Financial flows consolidation, expense tracking journals, and deep analytical reports to guide your strategies.',
    'hub.section.comptabilite_badge': 'Decision Steering',
    'hub.section.comptabilite_f1': 'Automatic net profit statement',
    'hub.section.comptabilite_f2': 'Structured billing/expense logs',
    'hub.section.comptabilite_f3': 'Gross revenue performance tracker',
    'hub.section.comptabilite_tag': 'Finance & Strategy',
    'hub.section.administration_title': 'Administration',
    'hub.section.administration_subtitle': 'Control & Security',
    'hub.section.administration_description': 'Secure employee management records, access levels setup, and global activity logger across your organization.',
    'hub.section.administration_badge': 'Secure & Compliant',
    'hub.section.administration_f1': 'Administrative staff listings',
    'hub.section.administration_f2': 'Custom roles assignment & permissions',
    'hub.section.administration_f3': 'Global business setup',
    'hub.section.administration_tag': 'Team & Roles',
    'hub.labels.operational_modules': 'Operational Modules',
    'hub.labels.management_pilot': 'Management & Guidance',
    'hub.labels.open_space': 'Open Workspace',
    'hub.labels.access': 'Access',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('fr');

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    try {
      const savedSettings = localStorage.getItem('smartAgro_settings');
      const settings = savedSettings ? JSON.parse(savedSettings) : {
        theme: 'light',
        colorTheme: 'farm',
        companyName: 'Smart Agro'
      };
      settings.language = lang;
      localStorage.setItem('smartAgro_settings', JSON.stringify(settings));
      window.dispatchEvent(new Event('settingsChanged'));
    } catch (e) {
      console.error(e);
    }
  };

  // Load language from local storage on mount
  useEffect(() => {
    const savedSettings = localStorage.getItem('smartAgro_settings');
    if (savedSettings) {
      try {
        const parsed = JSON.parse(savedSettings);
        if (parsed.language) {
          setLanguageState(parsed.language);
        }
      } catch (e) {
        console.error("Failed to parse settings", e);
      }
    }
  }, []);

  // Listen for storage changes (to sync across tabs/components if needed)
  useEffect(() => {
      const handleStorageChange = () => {
          const savedSettings = localStorage.getItem('smartAgro_settings');
          if (savedSettings) {
              const parsed = JSON.parse(savedSettings);
              if (parsed.language && parsed.language !== language) {
                  setLanguageState(parsed.language);
              }
          }
      };
      
      window.addEventListener('storage', handleStorageChange);
      // Custom event for same-tab updates
      window.addEventListener('settingsChanged', handleStorageChange);
      
      return () => {
          window.removeEventListener('storage', handleStorageChange);
          window.removeEventListener('settingsChanged', handleStorageChange);
      };
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
